# Generated by Django 5.0.7 on 2024-07-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeuser',
            options={'verbose_name': 'کاربران', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='customeuser',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='Users/images/'),
        ),
    ]
