# Generated by Django 5.0.7 on 2024-08-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_customeuser_options_customeuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, verbose_name='موبایل'),
        ),
    ]
