# Generated by Django 5.0.7 on 2024-08-03 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customeuser_date_time_shamsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='date_time_shamsi',
        ),
    ]
