# Generated by Django 5.0.7 on 2024-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'رنگ', 'verbose_name_plural': 'رنگ ها'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='productvariation',
            options={'verbose_name': 'ویژگی محصول', 'verbose_name_plural': ' ویژگی محصولات'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'سایز', 'verbose_name_plural': 'سایز'},
        ),
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(default='', max_length=30, unique=True),
        ),
    ]
