# Generated by Django 5.0.7 on 2024-08-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_color_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
