# Generated by Django 5.0.7 on 2024-08-03 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Slug',
        ),
    ]
