# Generated by Django 5.0.7 on 2024-08-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='price',
        ),
    ]
