# Generated by Django 5.0.7 on 2024-08-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_color_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
